### ISSUE TITLE
Linking the bridge as a secondary device is not working

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_signal_ynh#5] opened 2021-07-21 08:42 UTC
### Describe the bug

Linking the bridge as a secondary device is not working. 
`!sg link` is not working

### Context

- Hardware: *VPS bought online / Old laptop or computer 
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

In the "SIgnal bridge bot" room, I get an answer to the command `!sg help` but when I launch `!sg link` or `!sg link Matrix`, it fails with the following error :

> Unhandled error while handling command:

```
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix_signal/commands/auth.py", line 62, in link
    sess = await evt.bridge.signal.start_link()
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/signald.py", line 112, in start_link
    return LinkSession.deserialize(await self.request_v1("generate_linking_uri"))
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 210, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 200, in _raw_request
    await self._send_request(data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 190, in _send_request
    raise NotConnected("Not connected to signald")
mausignald.errors.NotConnected: Not connected to signald
```

### Expected behavior

Getting a QR code in order to link the bridge as a secondary device with the help of the Signal app

**Comment by Gredin67** [comment] 2021-07-21 12:29
I have the same issue. I think it is related to some signald user data remaining from a previous install, see https://gitlab.com/signald/signald/-/issues/187
Did you install for the first time or did you remove a previous signal installation beforehand?
Could you try to:
- remove signal_ynh
- erase signald user, group, and all related user data in debian
- re-install signal_ynh

**Comment by Thatoo** [comment] 2021-07-22 07:58
I have indeed tried to install as explained here https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/4 but it has failed.
Ok, I'll try to remove it and do what you said. 
To do "erase signald user, group, and all related user data in debian", could you give me the command I should launch?

**Comment by Thatoo** [comment] 2021-07-22 11:22
My question is about "all related user data in debian" mostly...

**Comment by Thatoo** [comment] 2021-07-22 13:57
I also need to delete the signalbot user in synapse I guess. How can I do that?

**Comment by Thatoo** [comment] 2021-07-22 14:44
Should I do
`curl --insecure -XPOST -H "Authorization: Bearer ACCES_TOKEN" -H "Content-Type: application/json" -d '{"erase": true}' "https://localhost:8448/_synapse/admin/v2/users/@signalbot:domain.com"`

**Comment by Thatoo** [comment] 2021-07-22 15:00
or because it's SSO, there is no need? we can still use the same user signalbot afterwards?

**Comment by Thatoo** [comment] 2021-07-23 09:05
For now, I did
```
sudo yunohost app remove mautrix_signal
sudo deluser signald
```
but I guess I should have done
`sudo deluser --remove-all-files signald`
and I did
```
sudo groupdel signald
sudo rm -R /var/lib/signald
```
but I got the following error : 

> rm: impossible to delete '/var/lib/signald': no file or folder

Now, before attempting a new install of this signal bridge, as it's on my prod server (I don't have test server...), I'd like to know what I should do with the @signalbot:domain.com user of my synapse server?
Will the installation take care of that, and be able to reuse this user or shoudl I do something about it?

**Comment by Thatoo** [comment] 2021-07-23 09:25
Or is @signalbot:domain.com a yunohost user that authenticate with SSO? I guess in that case their is no problem?

**Comment by centralscrutinizer21** [comment] 2021-08-02 17:11
`sudo signaldctl account delete (phone number)` did the trick for me

**Comment by centralscrutinizer21** [comment] 2021-08-02 17:17
I think the debian package is placing stuff in the wrong place, or the bridge is looking in the wrong place. I installed signlad from source and start it from the command line and the bridge works again, of course when closing the terminal the magic vanishes. If I try to move or soft link the program i get the same error again

**Comment by rosbeef** [comment] 2021-08-04 09:35
the only way i could connect mautrix to signald were to change access to signald folder with :
chmod 777 /var/run/signald

source : https://github.com/tulir/mautrix-signal/issues/45

**Comment by centralscrutinizer21** [comment] 2021-08-04 09:57
I see...but I don't even have that folder

**Comment by centralscrutinizer21** [comment] 2021-08-04 10:01
When I try to run signald from terminal (the one installed from debian repo) i get this error:
`Error: Could not find or load main class io.finn.signald.Main
Caused by: java.lang.ClassNotFoundException: io.finn.signald.Main`

**Comment by rosbeef** [comment] 2021-08-04 10:35
Is your instalation works well ?
Did you try as described in [#8 ](https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/8) ?
yunohost app remove mautrix_signal --debug
pip3 install --upgrade setuptools
yunohost app install mautrix_signal --debug
then
chmod 777 /var/run/signald

**Comment by centralscrutinizer21** [comment] 2021-08-04 11:16
yes installation goes well with the exeption of a few warnings:
`213101 WARNING   Failed building wheel for mautrix-signal`
`298022 WARNING ERROR:  column "signalbot" does not exist
298023 WARNING LINE 1: UPDATE users SET admin = 1 WHERE name = signalbot;
298023 WARNING`
pip3 install etc gives me
`Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/dist-packages (57.4.0)`
but at the end no /var/run/signald folder is created

**Comment by rosbeef** [comment] 2021-08-04 12:07
Last chance ... after that i'm not capable to help you :-1: 
could try before installing mautrix_signal
pip3 install --upgrade weel 

so : 

> yunohost app remove mautrix_signal --debug
> pip3 install --upgrade setuptools
> pip3 install --upgrade weel 
> yunohost app install mautrix_signal --debug
> then
> chmod 777 /var/run/signald

**Comment by centralscrutinizer21** [comment] 2021-08-04 12:10
can't upgrade wheel: `Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/weel/`

**Comment by rosbeef** [comment] 2021-08-04 12:12
sorry wheel

**Comment by centralscrutinizer21** [comment] 2021-08-04 12:24
yes I realized the command was missing the h after I posted my response.
But no that is not the problem, wheel upgraded but at installation I still get:
`204712 DEBUG   error: invalid command 'bdist_wheel'
204712 DEBUG
204713 DEBUG   ----------------------------------------
204713 WARNING   Failed building wheel for mautrix-signal`

**Comment by centralscrutinizer21** [comment] 2021-08-04 12:27
But the installation goes fine in the end, but when sending the bot the command link I get this error:
Unhandled error while handling command:

```traceback
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix_signal/commands/auth.py", line 62, in link
    sess = await evt.bridge.signal.start_link()
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/signald.py", line 112, in start_link
    return LinkSession.deserialize(await self.request_v1("generate_linking_uri"))
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 210, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 200, in _raw_request
    await self._send_request(data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 190, in _send_request
    raise NotConnected("Not connected to signald")
mausignald.errors.NotConnected: Not connected to signald
```
And it is definitely related to the bridge not able to connect to signald

**Comment by rosbeef** [comment] 2021-08-04 12:29
yes it show me this error but install is working for me.
and after chmod 777 /var/run/signald
!sg link works

damne i'm sorry i can not help more. i'm just a noob in debunging :P

**Comment by centralscrutinizer21** [comment] 2021-08-04 12:31
Thanks anyway. Maybe it's because I am running yunohost on a raspberry Pi 4 so armhf arch.
Dunno

**Comment by centralscrutinizer21** [comment] 2021-08-04 14:33
Just to understand, what's in your /var/run/synapse folder?

**Comment by rosbeef** [comment] 2021-08-05 08:22
/var/run/synapse does not exist

ls /var/run/**signald**
signald.sock
cat /var/run/signald/signald.sock 
cat: /var/run/signald/signald.sock: No such device or address

**Comment by Gredin67** [comment] 2021-08-05 22:45
reading this issue and discussion I feel like we have to implement what I describe in issue #9 to solve #5 and #8
If Someone wants to give it a try, feel free to open a new PR (from the testing branch)

**Comment by Gredin67** [comment] 2021-08-19 15:43
#17 solved

**Closed by Gredin67** 2021-08-19 15:43 UTC
